import { CodeGenerator } from './CodeGenerator.js';
import type { GeneratedCode, GeneratorOptions } from '../core/types.js';
import { Spec } from '../core/Spec.js';

export class MarkdownGenerator extends CodeGenerator {
  language = 'markdown';

  generate(spec: Spec, _options?: GeneratorOptions): GeneratedCode {
    const sections: string[] = [];

    sections.push(this.generateHeader(spec));
    sections.push(this.generateOverview(spec));
    sections.push(this.generateSchema(spec));
    sections.push(this.generateRequirements(spec));
    sections.push(this.generateConstraints(spec));
    sections.push(this.generateMetadata(spec));

    return {
      language: this.language,
      code: sections.filter(s => s.length > 0).join('\n\n'),
    };
  }

  private generateHeader(spec: Spec): string {
    return `# ${spec.name}

> **Version:** ${spec.version}
> **ID:** \`${spec.id}\`
> **Generated by:** LumiSDD

${spec.description || ''}`;
  }

  private generateOverview(spec: Spec): string {
    const completed = spec.getCompletedRequirements().length;
    const total = spec.requirements.length;
    const percentage = total > 0 ? Math.round((completed / total) * 100) : 0;

    return `## Overview

| Metric | Value |
|--------|-------|
| Total Requirements | ${total} |
| Completed | ${completed} |
| Compliance | ${percentage}% |
| Constraints | ${spec.constraints.length} |`;
  }

  private generateSchema(spec: Spec): string {
    if (!spec.schema) return '';

    return `## Schema

\`\`\`json
${JSON.stringify(spec.schema, null, 2)}
\`\`\``;
  }

  private generateRequirements(spec: Spec): string {
    if (spec.requirements.length === 0) return '';

    const sections: string[] = ['## Requirements'];

    const byPriority = {
      critical: spec.getRequirementsByPriority('critical'),
      high: spec.getRequirementsByPriority('high'),
      medium: spec.getRequirementsByPriority('medium'),
      low: spec.getRequirementsByPriority('low'),
    };

    for (const [priority, requirements] of Object.entries(byPriority)) {
      if (requirements.length === 0) continue;

      sections.push(`### ${this.capitalize(priority)} Priority`);

      for (const req of requirements) {
        sections.push(`#### ${req.id}: ${req.description}`);
        sections.push(`- **Status:** ${this.getStatusEmoji(req.status)} ${req.status}`);
        sections.push(`- **Testable:** ${req.testable ? '✅ Yes' : '❌ No'}`);

        if (req.acceptanceCriteria && req.acceptanceCriteria.length > 0) {
          sections.push('\n**Acceptance Criteria:**');
          for (const criteria of req.acceptanceCriteria) {
            sections.push(`- [ ] ${criteria}`);
          }
        }
      }
    }

    return sections.join('\n\n');
  }

  private generateConstraints(spec: Spec): string {
    if (spec.constraints.length === 0) return '';

    const sections: string[] = ['## Constraints'];

    const byType: Record<string, typeof spec.constraints> = {};
    for (const constraint of spec.constraints) {
      if (!byType[constraint.type]) byType[constraint.type] = [];
      byType[constraint.type].push(constraint);
    }

    for (const [type, constraints] of Object.entries(byType)) {
      sections.push(`### ${this.capitalize(type)}`);

      for (const constraint of constraints) {
        const severityIcon = constraint.severity === 'critical' ? '🔴' : constraint.severity === 'warning' ? '⚠️' : 'ℹ️';
        sections.push(`- ${severityIcon} **${constraint.id}:** ${constraint.description}`);
        sections.push(`  - \`${constraint.expression}\``);
      }
    }

    return sections.join('\n\n');
  }

  private generateMetadata(spec: Spec): string {
    if (Object.keys(spec.metadata).length === 0) return '';

    const sections: string[] = ['## Metadata'];

    for (const [key, value] of Object.entries(spec.metadata)) {
      sections.push(`- **${key}:** \`${value}\``);
    }

    return sections.join('\n');
  }

  private capitalize(str: string): string {
    return str.charAt(0).toUpperCase() + str.slice(1);
  }

  private getStatusEmoji(status: string): string {
    switch (status) {
      case 'completed': return '✅';
      case 'verified': return '✅✅';
      case 'in_progress': return '🔄';
      case 'rejected': return '❌';
      default: return '⏳';
    }
  }
}
