import { CodeGenerator } from './CodeGenerator.js';
import type { GeneratedCode, GeneratorOptions } from '../core/types.js';
import { Spec } from '../core/Spec.js';

export class TypeScriptGenerator extends CodeGenerator {
  language = 'typescript';

  generate(spec: Spec, options?: GeneratorOptions): GeneratedCode {
    const interfaces = this.generateInterfaces(spec);
    const types = this.generateTypes(spec);
    const enums = this.generateEnums(spec);
    const validators = this.generateValidators(spec);

    const code = `/**
 * ${spec.name} - ${spec.description || 'Generated from LumiSDD'}
 * Version: ${spec.version}
 * Auto-generated by LumiSDD
 */

${interfaces}

${types}

${enums}

${validators}

export * from './types';
export * from './validators';
`;

    return {
      language: this.language,
      code: this.sanitizeCode(code),
    };
  }

  private generateInterfaces(spec: Spec): string {
    if (!spec.schema || typeof spec.schema !== 'object') {
      return '';
    }

    const lines: string[] = ['// Interfaces'];
    lines.push(`export interface ${this.toPascalCase(spec.name)} {`);

    const schema = spec.schema as Record<string, unknown>;
    if (schema.properties) {
      const props = schema.properties as Record<string, Record<string, unknown>>;
      for (const [key, value] of Object.entries(props)) {
        const required = (schema.required as string[] || []).includes(key);
        const type = this.mapJsonSchemaToTs(value);
        lines.push(`  ${this.escapeKeyword(key)}${required ? '' : '?'}: ${type};`);
      }
    }

    lines.push('}');
    return lines.join('\n');
  }

  private generateTypes(spec: Spec): string {
    const lines: string[] = ['// Types'];

    for (const req of spec.requirements) {
      if (req.acceptanceCriteria && req.acceptanceCriteria.length > 0) {
        const typeName = this.toPascalCase(req.id);
        lines.push(`export type ${typeName}Status = ${req.acceptanceCriteria.map(() => "'pending' | 'completed'").join(' | ').replace("'pending' | 'completed' | ", '')};`);
      }
    }

    return lines.join('\n');
  }

  private generateEnums(spec: Spec): string {
    const lines: string[] = ['// Enums'];

    const priorityEnum = spec.requirements.length > 0;
    if (priorityEnum) {
      lines.push("export enum Priority {");
      lines.push("  Critical = 'critical',");
      lines.push("  High = 'high',");
      lines.push("  Medium = 'medium',");
      lines.push("  Low = 'low'");
      lines.push("}");
    }

    const statusEnum = spec.requirements.length > 0;
    if (statusEnum) {
      lines.push("export enum RequirementStatus {");
      lines.push("  Pending = 'pending',");
      lines.push("  InProgress = 'in_progress',");
      lines.push("  Completed = 'completed',");
      lines.push("  Verified = 'verified',");
      lines.push("  Rejected = 'rejected'");
      lines.push("}");
    }

    return lines.join('\n');
  }

  private generateValidators(spec: Spec): string {
    const lines: string[] = ['// Validators'];

    lines.push(`export function create${this.toPascalCase(spec.name)}Validator() {`);
    lines.push(`  return function validate(data: unknown): data is ${this.toPascalCase(spec.name)} {`);
    lines.push(`    if (!data || typeof data !== 'object') return false;`);
    lines.push('    return true;');
    lines.push('  };');
    lines.push('}');

    return lines.join('\n');
  }

  private mapJsonSchemaToTs(schema: Record<string, unknown>): string {
    if (schema.type === 'string') return 'string';
    if (schema.type === 'number' || schema.type === 'integer') return 'number';
    if (schema.type === 'boolean') return 'boolean';
    if (schema.type === 'array') {
      const itemType = schema.items ? this.mapJsonSchemaToTs(schema.items as Record<string, unknown>) : 'unknown';
      return `${itemType}[]`;
    }
    if (schema.type === 'object') return 'Record<string, unknown>';
    if (schema.$ref) return this.extractRefName(schema.$ref as string);
    if (schema.enum) return schema.enum.map((v: unknown) => `'${v}'`).join(' | ');
    return 'unknown';
  }

  private extractRefName(ref: string): string {
    const parts = ref.split('/');
    return parts[parts.length - 1] || 'unknown';
  }

  private sanitizeCode(code: string): string {
    return code
      .replace(/\n{3,}/g, '\n\n')
      .replace(/^$\n/gm, '')
      .trim();
  }
}
