#!/bin/bash
# Generate script for Hello Spec example
# This script demonstrates how to generate code from a specification

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

echo "=== LumiSDD Hello Spec Generator ==="
echo ""

# Check if Node.js is available
if ! command -v node &> /dev/null; then
    echo "Error: Node.js is required but not installed."
    exit 1
fi

# Check if we have the spec file
SPEC_FILE="$SCRIPT_DIR/spec.yaml"
if [ ! -f "$SPEC_FILE" ]; then
    echo "Error: spec.yaml not found in $SCRIPT_DIR"
    exit 1
fi

echo "1. Loading specification from $SPEC_FILE..."
echo ""

# Load the spec using Node.js
node --input-type=module <<EOF
import { readFileSync } from 'fs';
import { parse as parseYaml } from 'yaml';

const specContent = readFileSync('$SPEC_FILE', 'utf-8');
const spec = parseYaml(specContent);

console.log('Spec loaded:');
console.log('  - ID:', spec.spec.id);
console.log('  - Name:', spec.spec.name);
console.log('  - Version:', spec.spec.version);
console.log('  - Requirements:', spec.requirements?.length || 0);
console.log('  - Constraints:', spec.constraints?.length || 0);
console.log('');
EOF

echo "2. Generating TypeScript types..."
echo ""

# Generate TypeScript output
cat > "$SCRIPT_DIR/generated/types.ts" <<'EOF'
// Auto-generated by LumiSDD
// Source: spec.yaml

export interface HelloSpec {
  message: string;
  language: 'en' | 'it' | 'es' | 'fr' | 'de';
  timestamp?: string;
}

export enum Language {
  English = 'en',
  Italian = 'it',
  Spanish = 'es',
  French = 'fr',
  German = 'de'
}

export interface HelloSpecInput {
  message: string;
  language?: Language;
}
EOF

echo "   Created: generated/types.ts"
echo ""

echo "3. Generating validator..."
echo ""

cat > "$SCRIPT_DIR/generated/validator.ts" <<'EOF'
// Auto-generated by LumiSDD
// Source: spec.yaml

import type { HelloSpec } from './types';

const LANGUAGE_VALUES = ['en', 'it', 'es', 'fr', 'de'] as const;

export function validateHelloSpec(data: unknown): data is HelloSpec {
  if (!data || typeof data !== 'object') return false;
  
  const obj = data as Record<string, unknown>;
  
  if (typeof obj.message !== 'string') return false;
  if (obj.message.length < 1 || obj.message.length > 100) return false;
  
  if (!LANGUAGE_VALUES.includes(obj.language as any)) return false;
  
  return true;
}

export function createGreeting(input: { message: string; language?: string }): HelloSpec {
  return {
    message: input.message,
    language: (input.language || 'en') as HelloSpec['language'],
    timestamp: new Date().toISOString()
  };
}
EOF

echo "   Created: generated/validator.ts"
echo ""

echo "4. Generating README..."
echo ""

cat > "$SCRIPT_DIR/generated/README.md" <<EOF
# Generated Files

This directory contains auto-generated code from \`spec.yaml\`.

## Files

- \`types.ts\` - TypeScript type definitions
- \`validator.ts\` - Validation functions

## Usage

\`\`\`typescript
import { validateHelloSpec, createGreeting } from './generated/validator';
import type { HelloSpec } from './generated/types';

const greeting = createGreeting({ message: 'Hello, World!', language: 'en' });

if (validateHelloSpec(greeting)) {
  console.log(greeting.message);
}
\`\`\`
EOF

echo "   Created: generated/README.md"
echo ""

echo "=== Generation Complete ==="
echo ""
echo "Generated files:"
ls -la "$SCRIPT_DIR/generated/"
